meta-handheld: add dependency on openembedded-layer
With commit d37f6b5 "tslib: remove recipe" tslib was moved from oe-core
to meta-oe. Add dependency on that layer to fix:

ERROR: Required build target 'core-image-base' has no buildable providers.
Missing or unbuildable dependency chain was:
 ['core-image-base', 'packagegroup-base-extended', 'zaurusd', 'tslib']

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>