encdec-updater: remove COMPATIBLE_MACHINE
The recipe is using BBCLASSEXTEND = "native" and as it is not buildable:

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'encdec-updater-native'
 (but /oe/meta-handheld/recipes-bsp/zaurus-utils/zaurus-updater.bb
  DEPENDS on or otherwise requires it)
ERROR: encdec-updater-native was skipped: incompatible with machine poodle
 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'zaurus-installer' has no buildable providers.
Missing or unbuildable dependency chain was:
 ['zaurus-installer', 'zaurus-updater', 'encdec-updater-native']

Remove COMPAIBLE_MACHINE alltogether.
While there, remove PR remnant.

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>